const Portfolio_data = [
    {
        id: 1,
        category: "Full Stack DEVELOPMENT",
        totalLike: "200",
        title: "Online Doctor appoinment website (Full Stack)",
        image: "https://i.ibb.co/P5fhPsd/Blue-Modern-Medical-Banner-Landscape.png",
        discription: '➔➔➔ A full stack project where patients can book appointments at different times and slots ➔➔➔ Applied Dashboard for User Who can see their booking status Time and date also ➔➔➔ Admin section added, An admin can add or remove a doctor.➔➔➔ Patient take appoinments from Doctor.',
        tecnology: 'Tecnology::-- JavaScript, Tailwinds, Daisyui, React js (Router, Hooks, Toastify, query, hook-form, day-picker), JWT, Protected Route, Firebase Authentication, Nodejs, Express, MongoDB',
        live: 'https://doctors-portal-ae6e1.web.app/',
        gitui: 'https://github.com/Habibullah800/Doctors-portal-client-cv',
        gitserver: 'https://github.com/Habibullah800/Doctor-portal-server-cv',
    },
    {
        id: 2,
        category: "Front-End with Redux",
        totalLike: "90",
        title: "Online E-Commerce with Cart Funtionality",
        image: "https://i.ibb.co/6X5WfvB/pizzaworld-com-1.png",
        tecnology: 'Tecnology::-- JavaScript, React, Redux Tailwinds, Daisyui, Material-UI, React-Router, React-Toastify, React-Redux, Styled-Components, Font-Awesome, Babel-Plugin-Macros',
        discription: '➔➔➔ A React-Redux project where Buyer can add Burger or fod item in cart.➔➔➔ When click on the cart will see a modal there will see all items that he added to the cart last time.➔➔➔ Then if he click on specific item a new page will open, There will be all the description of the product & he can increase or decrease quantity.➔➔➔ Everything will be stored in local storage for later use.',
        tecnology: 'Tecnology::-- JavaScript, Tailwinds, Daisyui, React js (Router, Hooks, Toastify, query, hook-form, day-picker), JWT, Protected Route, Firebase Authentication, Nodejs, Express, MongoDB',
        live: 'https://burger-world22.netlify.app/',
        gitui: 'https://github.com/Habibullah800/E-Commerce-CartApp-React-Redux',
        gitserver: 'https://github.com/Habibullah800/E-Commerce-CartApp-React-Redux',
    },

    {
        id: 3,
        category: "Full-Stack Projects with React",
        totalLike: "90",
        title: " Inventory manage Website (Full-Stack)",
        image: "https://i.postimg.cc/RhcrnZJ0/100-Healthy-Affordable-11zon.png",
        discription: '➔➔➔ This website is about tracking the products in the warehouse. ➔➔➔ After logging in, the user could update the stock of the product. ➔➔➔➔ The user could add products and have seen their added products, and manage them.',
        tecnology: 'Tecnology::-- JavaScript, React, Bootstrap, React-Router, React-Hook-Form, React-Router-Dom, React-Toastify, Firebase Authentication, Font-Awesome, Dotenv, Cors, Express, MongoDB ',
        live: 'https://grocery-store-cbc0a.web.app/home',
        gitui: 'https://github.com/Habibullah800/warehouse-manage-client-cv',
        gitserver: 'https://github.com/Habibullah800/Warehouse-Managment-server-cv/tree/master',
    },

    {
        id: 4,
        category: "Front-End Website develop",
        totalLike: "630",
        title: "VARAL UAE Company Feature Website Develop with React",
        image: "https://i.ibb.co/wYbj8tp/Varal-UAE-min.png",
        tecnology: 'Tecnology::-- JavaScript, React, Tailwind, Font-Awesome',
        discription: ' ➔➔➔ It is a landing page using React.➔➔➔No other framework or CMS were used in this landing page. ➔➔➔It is fully responsive for any kind of screen size. Here used CSS Media Queries. ➔➔➔Used the Google font “Lexand Deca” in the Header and “NotoSans” in the remaining area of this Landing page.',
        live: 'https://varal-uae.netlify.app/',
        gitui: 'https://github.com/Habibullah800/varal-uae-ui',
        gitserver: 'https://github.com/Habibullah800/varal-uae-ui',
    },
    {
        id: 5,
        category: "Full-Stack Website",
        totalLike: "30",
        title: "Manufecturer website develop with React (Full-Stack)",
        tecnology: 'Tecnology::-- JavaScript, Tailwinds, Daisyui, React js (Router, Hooks, Toastify, query), Protected Route, Firebase Authentication, Nodejs, Express, MongoDB',
        discription: '➔➔➔ A full stack project where admin add any product➔➔➔After Log-in Customer search any product add product to cart ➔➔➔ Admin section added, An admin can add or remove a product.➔➔➔ User can see their DashBoard',
        image: "https://i.ibb.co/m8FWsCs/Manufecture-Website-min.png",
        gitui: 'https://github.com/Habibullah800/Manufacture-website-client-site-cv',
        gitserver: 'https://github.com/Habibullah800/Manufecture-website-server-site-cv',
    },
    {
        id: 6,
        category: "Front-End Developments",
        totalLike: "70",
        title: "Portfolio website develop with React Js",
        tecnology: 'Tecnology::-- HTML, Vanila CSS, JavaScript, Tailwinds, React js, React Router Dom, Font Awesome',
        discription: ' ➔➔➔ It is a landing page using React.➔➔➔No other framework or CMS were used in this landing page. ➔➔➔It is fully responsive for any kind of screen size. Here used CSS Media Queries.',
        image: "https://i.ibb.co/XWVDNJM/welcome-packet.png",
    },

]
export default Portfolio_data
