const BlogApi = [
    {
        id: 1,
        image: "https://i.ibb.co/8cSGS6n/4.png",
        date: "2 May, 2021",
        title_one: "Why I am recomanded to use redux in react app?",
        desc_one: "When using Redux with React, states will no longer need to be lifted up. This makes it easier for you to trace which action causes any change. As you can see in the example above, the component does not need to provide any state or method for its children components to share data among themselves. Everything is handled by Redux. This greatly simplifies the app and makes it easier to maintain. This is the primary reason why you should use Redux, but it’s not the only benefit.",
        title_two: "What is Redux?",
        desc_two: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments, and are easy to test.While it’s mostly used as a state management tool with React, you can use it with any other JavaScript framework or library. It’s lightweight at 2KB (including dependencies), so you don’t have to worry about it making your application’s asset size bigger.With Redux, the state of your application is kept in a store, and each component can access any state that it needs from this store. Take a look at the list below for a summary of what you stand to gain by using Redux for state management.",
        title_three: "Redux makes the state predictable.",
        desc_three: "In Redux, the state is always predictable. If the same state and action are passed to a reducer, the same result is always produced because reducers are pure functions. The state is also immutable and is never changed. This makes it possible to implement arduous tasks like infinite undo and redo. It is also possible to implement time travel — that is, the ability to move back and forth among the previous states and view the results in real time.",

        title_four: "Redux is maintainable.",
        desc_four: "Redux is strict about how code should be organized, which makes it easier for someone with knowledge of Redux to understand the structure of any Redux application. This generally makes it easier to maintain. This also helps you segregate your business logic from your component tree. For large scale apps, it’s critical to keep your app more predictable and maintainable.",

        title_five: "Performance benefits.",
        desc_five: "You might assume that keeping the app’s state global would result in some performance degradation. To a large extent, that’s not the case. React Redux implements many performance optimizations internally so that your own connected component only rerenders when it actually needs to. Thats why we can use Redux",
    },
    {
        id: 2,
        image: "https://i.ibb.co/R2KxWmm/React1.jpg",
        date: "28 April, 2021",
        title_one: "Why Should I Use React for Web Development? ",
        desc_one: "React is a free, open-source JavaScript library for building User Interfaces. It is used to build single-page applications and allows you to create reusable UI components. You can build some brilliant and responsive websites using React.",
        title_two: "What is React? ",
        desc_two: "React is a popular library. Before React, Angular JS, Ember JS, and Ajax were taking the privilege of web and app development.The main reason why React is so popular is that it offers developers an easy way to create applications with a lot of functionality at once. This means that your app doesn’t need to be as complicated as other frameworks; instead, you can focus on building features in your app rather than how to get those features up and running on the web. This can help make your app easier for users to understand and use! There are multiple platforms based on React to create web applications, mobile applications, and cross-hybrid platforms for desktops.Another benefit of using React is that it doesn’t require any knowledge of HTML or CSS before getting started with development.",
        title_three: "Easy To Learn",
        desc_three: "This is perhaps the most important advantage that comes with choosing React as a framework. It’s very easy to learn, so you’ll save a lot of time on training your teams or other developers on how to use it effectively. And this is one of the best reasons why you should choose React for web development. Even if you’re new to web development, React can be learned quickly and easily because it doesn’t require special skills or experience—just basic HTML, CSS, and JavaScript knowledge.",
        title_four: "Faster To Build",
        desc_four: "Because of its component-based approach and virtual DOM, React is a lot faster than other frameworks. This means that you won’t have to spend much time developing your app or website. Internally, React employs several unique options to minimize the frequency of costly DOM operations needed to refresh the UI. That is the reason why for many applications, using React will lead to a fast user interface without doing much work to specifically optimize for performance.",
        title_five: "SEO Friendliness",
        desc_five: "As React runs over a server and returns a virtual DOM request while browsing, it makes the web pages light for the search engine crawlers to crawl through the web pages and ultimately makes it easier to rank. The other web pages with Javascript codes with heavy applications make the search engine a little hard to crawl through and make it less supportive of SEO ranking.",
    },
    {
        id: 3,
        image: "https://i.ibb.co/CtVRQ9s/React-Vs-Angular-Which-Is-Better-For-Your-App-1.jpg",
        date: "20 Jun, 2021",
        title_one: "How is React different from Angular?",
        desc_one: "React is a JavaScript library, whereas Angular is a front-end framework. React uses one-way data binding and virtual DOM, whereas Angular uses two-way data binding and real DOM. Moreover, React is faster than Angular as it has a smaller bundle size.",
        title_two: "Advantages of React JS.",
        desc_two: "React JS offers many excellent front-end benefits to users and developers. Here are some of the prime advantages of React JS you can leverage: React offers an easy debugging process. The code is reusable. It’s easy to learn because of its easy and simple design. It allows developers to migrate an app in React very easily. It supports both Android and iOS platforms. ReactJS is view- oriented. It has faster updates with both server - side and front - end support. It supports a React Native library that offers efficient performance.",
        title_three: "Benefits of Angular",
        desc_three: "Let’s understand the benefits of Angular: Angular offers clean code development and dependency injection. You can use many Angular libraries, which help you create robust template solutions. To execute a unit test in Angular, you need to inject mock data into the controller, then inspect the result and its behavior. Also, it allows you to create every single page separately and then combine them with the components to view the final product. It offers a single routing option. Also, it has interactive UIs with data binding. Angular extends HTML syntax. With directives, Angular lets you create reusable components. Must have synchronized data between the model view and the component.",
        title_four: "React JS vs Angular: When to Choose What?",
        desc_four: 'Angular is better than React if your application is enterprise-grade and you need to incorporate complex functionalities like progressive, single-page, and native web apps. However, React specializes in creating UI components and can be used in any application, including single-page apps.',
        title_five: "Angular or React - Which is Better?",
        desc_five: "Both Angular and React are the most popular front-end technologies in the developer’s community. They offer several amazing benefits but React works better than Angular. Moreover, a huge development community supports React JS. Since React consists of Virtual DOM and renders optimizations, it surpasses Angular in the battle of comparison. Also, it enables developers to migrate between React versions without any hassle. Unlike Angular, it has a very easy and simple installation process. In a nutshell, React offers many advantages and robust solutions for developers, which enhances the development time and eliminates errors. So, while choosing the suitable front end technology from React vs Angular, you should consider it based on your usages, project requirements, and functionalities.",
    },
]
export default BlogApi
